# TODO 1: ajouter les directives generales
# https://github.com/actions/starter-workflows/blob/main/ci/rust.yml

name: Rust 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO 7: utiliser le secret
      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
      # - name: Write private key to file
      # TODO 2: ajouter les taches de compilation
      # https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
